import type { Product } from './types';

type Policy = { summary: string; sources: { label: string; url: string }[] };
// Policies reviewed on 2026-10-09. These summaries are not a model certificate.
export const warrantyPolicies: Record<string, Policy> = {
  LG: { summary: 'Linhas residenciais elegíveis: 2 anos no aparelho para compras a partir de 01/09/2025; compras anteriores: 1 ano. Compressor: 10 anos somente quando previsto no certificado. Linhas comerciais têm regras próprias. A elegibilidade depende do código e do certificado do modelo.', sources: [{label:'Política oficial LG',url:'https://www.lg.com/br/suporte/garantia/'}] },
  Samsung: { summary: 'Linha residencial RAC: 1 ano no aparelho; WindFree PowerVolt: 2 anos. Compressor Inverter RAC: 10 anos conforme termo. Linhas CAC e Multi Conexões FJM: 1 ano, inclusive compressor. VRF DVM possui regras próprias. Confirme a linha e o certificado do modelo.', sources: [{label:'Política oficial Samsung',url:'https://www.samsung.com/br/support/warranty/'}] },
  Gree: { summary: 'Modelos elegíveis: 5 anos no produto e 10 anos no compressor, conforme certificado. A garantia contratual exige instalação por assistência autorizada ou instalador credenciado quando previsto, comprovantes e cumprimento do manual. Sem as condições contratuais, a política informa garantia legal de 90 dias.', sources: [{label:'Política oficial Gree',url:'https://loja.gree.com.br/pagina/politica-de-garantia/'}] },
  Midea: { summary: 'O prazo varia por linha. A política Midea prevê 90 dias legais mais 9 ou 21 meses contratuais, conforme modelo e instalação. AI AirVolution consultado: 2 anos no produto com instalação credenciada/certificada e cumprimento do manual. Não se deve atribuir 10 anos ao compressor sem certificado específico.', sources: [{label:'Política oficial Midea',url:'https://www.midea.com/br/politica_de_servicos'},{label:'AI AirVolution 9.000 — CentralAr',url:'https://www.centralar.com.br/p/ar-condicionado-split-hi-wall-inverter-r-32-ai-airvolution-midea-9000-btus-frio-220v-monofasico-42efvca09m5'},{label:'AI AirVolution 18.000 — Leveros',url:'https://www.leveros.com.br/ar-condicionado-split-hw-inverter-midea-ai-airvolution-18-000-btus-r-32-so-frio-220v'}] },
  Daikin: { summary: 'EcoSwing R32/Full Inverter residencial consultado: 2 anos no aparelho e 10 anos no compressor. SkyAir, Multi Split Smart R32 e Advance consultados: 2 anos no aparelho e 5 anos no compressor. O certificado e as condições de instalação do modelo determinam a cobertura.', sources: [{label:'EcoSwing — Daikin',url:'https://www.daikin.com.br/produto/ecoswing-r32'},{label:'SkyAir — Daikin',url:'https://www.daikin.com.br/produto/skyair-r32'},{label:'Multi Split — Daikin',url:'https://www.daikin.com.br/produto/multi-split-smart-r-32'}] },
  Elgin: { summary: 'Split Hi Wall, Cassete e Piso Teto elegíveis: 3 anos com instalação por empresa credenciada. Split Hi Wall Inverter elegível: 10 anos no compressor com instalação credenciada. Verifique a data de compra, o manual e o certificado do modelo.', sources: [{label:'Política Elgin',url:'https://blog.elgin.com.br/ar-condicionado/nova-garantia-ar-condicionado-elgin/'}] },
  Fujitsu: { summary: 'A linha Hi Wall Premium consultada informa 2 anos para peças e componentes e 5 anos para compressor. Outras linhas podem ter condições diferentes. Confirme o código e o certificado antes da compra.', sources: [{label:'Hi Wall Premium — Fujitsu',url:'https://loja.br.fujitsu-general.com/linha-premium/hi-wall'}] },
  TCL: { summary: 'Modelos elegíveis: até 2 anos no aparelho e 10 anos no compressor Inverter, com instalação credenciada TCL. Para os 10 anos do compressor, a TCL exige também manutenção anual por credenciado e registro no manual. Confira o certificado específico.', sources: [{label:'Garantia — TCL',url:'https://www.tcl.com/br/pt/support-airconditioner/faq/17762'},{label:'Condições do compressor — TCL',url:'https://www.tcl.com/br/pt/support-airconditioner/faq/17746'}] },
  Hisense: { summary: 'As páginas oficiais Hi-Smart, Hi-Efficiency, Cassete e Piso Teto consultadas anunciam 10 anos no compressor Inverter. O prazo do aparelho e as condições precisam ser confirmados no certificado do modelo; os 10 anos não representam garantia integral do aparelho.', sources: [{label:'Hi-Smart — Hisense',url:'https://hisense.com.br/ar-condicionado/split-hi-smart/'},{label:'Cassete — Hisense',url:'https://hisense.com.br/ar-condicionado/corporativos-cassete/'}] },
  Electrolux: { summary: 'MaxComfort NI12F/NE12F e NI12R/NE12R consultados: 5 anos no produto e 10 anos no compressor, conforme condições do fabricante, inclusive com instalador não credenciado. Color Adapt tem certificado próprio; não estenda os prazos de MaxComfort a outra linha.', sources: [{label:'MaxComfort NI12F/NE12F — Electrolux',url:'https://loja.electrolux.com.br/ar-condicionado-split-electrolux-maxcomfort-full-inverter-frio-12-000-btus-ni12f-ne12f/p'},{label:'Color Adapt JI12F/JE12F — Electrolux',url:'https://loja.electrolux.com.br/ar-condicionado-split-electrolux-inverter-12000-btus-color-adapt-frio-ji12f-je12f/p'}] },
  Agratto: { summary: 'Zen Inverter 9.000 R32 consultado: 90 dias legais, estendidos para 1 ano nas unidades interna e externa quando instalado pela rede credenciada Agratto, com nota fiscal de instalação e demais comprovantes. Não aplique esse prazo automaticamente a outras linhas.', sources: [{label:'Zen Inverter 9.000 — Leveros',url:'https://www.leveros.com.br/ar-condicionado-split-hw-inverter-agratto-zen-9-000-btus-r-32-so-frio-220v'}] },
  Philco: { summary: 'Prazo específico pendente de confirmação pelo código do fabricante e certificado. A orientação oficial exige profissional homologado para instalação. Consulte as condições do modelo antes da compra.', sources: [{label:'Orientações oficiais Philco',url:'https://campanhas.philco.com.br/guia-completo-de-ar-condicionado/'}] },
};
for (const brand of ['Springer Carrier', 'Carrier', 'Hitachi']) {
  warrantyPolicies[brand] = { summary: 'Consulte o prazo do aparelho e do compressor no certificado do modelo. Não há prazo específico confirmado para este cadastro. Informe o código da evaporadora e da condensadora para conferir as condições de instalação e cobertura.', sources: [] };
}
export function getWarrantyPolicy(brand: string): Policy {
  return warrantyPolicies[brand] || { summary: 'Confirmar com o consultor de vendas, conforme certificado do fabricante.', sources: [] };
}
export function applyWarrantyPolicy(product: Product): Product {
  const warranty = 'Confirmar com o consultor de vendas';
  const clean = (text: string) => text.replace(/com\s+\d+\s+anos?\s+de\s+garantia/gi, 'com garantia conforme certificado');
  return {...product, warranty, description: clean(product.description), features: product.features.map(clean), specs: Object.fromEntries(Object.entries(product.specs).map(([key,value]) => [key, /garantia/i.test(key) ? warranty : clean(value)]))};
}
